console.log(3 - "1");
console.log(3 * "2");
console.log(3 / "6");
console.log("3" < 0);
console.log("3" > 0);
console.log(NaN > 0);
console.log(NaN < 0);
console.log(undefined < 0);
console.log(undefined > 0);