console.log(typeof "Hello");
console.log(typeof 1);
console.log(typeof true);
console.log(typeof undefined);
console.log(typeof Symbol("MySymbol"));
console.log(typeof {});
console.log(typeof []);
console.log(typeof new Date());
console.log(typeof function() {});
console.log(typeof null);